version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: webgis-app
        container_name: webgis-app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - webgis-network
        ports:
            - "5173:5173" # Untuk Vite HMR jika diperlukan

    webserver:
        image: nginx:alpine
        container_name: webgis-webserver
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - webgis-network
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: webgis-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: webgis
            MYSQL_USER: yppsb
            MYSQL_PASSWORD: yppsbjuara21
            MYSQL_ROOT_PASSWORD: rootpassword
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - webgis-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: webgis-phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            MYSQL_USER: yppsb
            MYSQL_PASSWORD: yppsbjuara21
            MYSQL_ROOT_PASSWORD: rootpassword
        ports:
            - "8080:80"
        depends_on:
            - db
        networks:
            - webgis-network

volumes:
    dbdata:
        driver: local

networks:
    webgis-network:
        driver: bridge
