version: "3.8"

services:
    app:
        build:
            context: ./docker/php
        container_name: laravel-app
        working_dir: /var/www
        volumes:
            - ./src:/var/www
        networks:
            - laravel
        depends_on:
            - mysql

    nginx:
        image: nginx:alpine
        container_name: laravel-nginx
        ports:
            - "8000:80"
            - "5173:5173" # Vite dev server
        volumes:
            - ./src:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    node:
        image: node:18
        container_name: laravel-node
        working_dir: /var/www
        volumes:
            - ./src:/var/www
        networks:
            - laravel
        command: sh -c "npm install && npm run dev"

    mysql:
        image: mysql:8.0
        container_name: laravel-mysql
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
        networks:
            - laravel

networks:
    laravel:

volumes:
    mysql-data:
